# Generated by Django 2.0 on 2017-12-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
