# Generated by Django 2.0.1 on 2018-03-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_ratingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spot',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
