# Generated by Django 2.0.1 on 2018-03-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20180305_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.RatingType')),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Spot')),
            ],
        ),
    ]
