# Generated by Django 2.0.1 on 2018-03-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating_type_id',
            new_name='rating_type',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='spot_id',
            new_name='spot',
        ),
    ]
