# Generated by Django 2.0.1 on 2018-03-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20180305_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating_type',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
