# Generated by Django 2.0.1 on 2018-03-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20180305_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rating_type',
        ),
    ]
